### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by jwalkerbg** [mhaseebkhan/redmine_socio_connect#1]
I got Internal server error.
Configuration: Redmine latest trunk, rev  12220, Ruby 1.9.3, thin server, using only redmine_socio_connect plugin (all others removed so as to test clean).
On http://path/to/redmine:3000 received

---

Connecting to database specified by database.yml
Creating scope :system. Overwriting existing method Enumeration.system.
Creating scope :sorted. Overwriting existing method Group.sorted.
Creating scope :sorted. Overwriting existing method User.sorted.
Started GET "/" for 192.168.142.1 at 2013-10-13 16:34:22 +0300
Processing by WelcomeController#index as HTML
  Current user: imc (id=3)
  Rendered news/_news.html.erb (46.0ms)
  Rendered welcome/index.html.erb within layouts/base (182.5ms)
  Rendered plugins/redmine_socio_connect/app/views/shared/_socio_connect.html.erb (2.0ms)
Completed 500 Internal Server Error in 452ms

ActionView::Template::Error (undefined method `[]' for nil:NilClass):
    13:    
    14:    facebook_keys_present = !$socio_connect_settings['facebook']['key'].blank? && !$socio_connect_settings['facebook']['secret'].blank? ? true : false
    15:    
    16:    github_keys_present = !$socio_connect_settings['github']['key'].blank? && !$socio_connect_settings['github']['secret'].blank? ? true : false
    17: %>
    18: var twitter_Btn = '', facebook_Btn = '', github_Btn = '';
    19: <% if twitter_keys_present %>
  lib/redmine/hook.rb:111:in`block in render_on'
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in`each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in`tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:158:in`call_hook'
  app/views/layouts/base.html.erb:14:in `_app_views_layouts_base_html_erb___743235809_43862172'

---

**Comment by mhaseebkhan** [comment]
Let me test and get back to you as soon as I can.

**Comment by mhaseebkhan** [comment]
I have tested it on redmine 2.3.2 and 2.3.3. The plugin is working fine.

Kindly give a break down of the steps that you used to run the plugin.

Kindly make sure that you have configured redmine properly, also migrated the databases for redmine and plugin as well.

**Comment by onlymeee** [comment]
I get exactly the same error messages with the same stack trace at the end. I'm running Redmine 2.6.3 on Linux with ruby 1.9.3p429, rails 3.2.21, Apache 2.2.29 and Phusion Passenger 5.0.5 and apart from this plugin, the installation is working fine. There are no other Redmine plugins installed. Installation steps I took were:
- I installed the plugin in the plugins directory
- I fetched the plugin dependencies using bundle install (ran OK)
- I migrated the database for plugin (ran OK)
- I set up the Facebook app ID and key in the plugin's settings.yml
- I restarted Redmine

**Comment by mtolava** [comment]
I have the same issue for Redmine 3.0 in Linux. It is a fresh installation and I have run all the migrates.
